name: VanillaTweaks
version: '1.0.0-SNAPSHOT'
main: de.remadisson.vanillatweaks.VanillaTweaks
api-version: '1.20'
authors: [ "remadisson" ]
website: [ "https://www.remady.me" ]
commands:
  tpa:
    permission: "vt.tpa.there"
    description: "§e/tpa §7<§bPlayer§7>"
  tpahere:
    permission: "vt.tpa.here"
    description: "§e/tpahere §7<§bPlayer§7>"
  tpaaccept:
    permission: "vt.tpa.accept"
    description: "§e/tpaaccept §7<§bPlayer§7>"
  tpadecline:
    permission: "vt.tpa.decline"
    description: "§e/tpadecline §7<§bPlayer§7>"
  home:
    permission: "vt.homes.home"
    aliases: [ "homes" ]
    description: "§e/home §7<§bHome§7>"
  sethome:
    permission: "vt.homes.sethome"
    description: "§e/setHome §7<§bName§7>"
  delhome:
    permission: "vt.homes.delhome"
    description: "§e/delhome §7<§bHome§7>"